/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.2-SNAPSHOT on 2009-12-16 07:21:29,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.plexus.components.sec.dispatcher.model;

/**
 * Named configuration.
 * 
 * @version $Revision$ $Date$
 */
public class Config
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * name of this configuration.
     */
    private String name;

    /**
     * Field properties.
     */
    private java.util.List/*<ConfigProperty>*/ properties;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addProperty.
     * 
     * @param configProperty
     */
    public void addProperty( ConfigProperty configProperty )
    {
        getProperties().add( configProperty );
    } //-- void addProperty( ConfigProperty )

    /**
     * Get name of this configuration.
     * 
     * @return String
     */
    public String getName()
    {
        return this.name;
    } //-- String getName()

    /**
     * Method getProperties.
     * 
     * @return List
     */
    public java.util.List/*<ConfigProperty>*/ getProperties()
    {
        if ( this.properties == null )
        {
            this.properties = new java.util.ArrayList/*<ConfigProperty>*/();
        }

        return this.properties;
    } //-- java.util.List/*<ConfigProperty>*/ getProperties()

    /**
     * Method removeProperty.
     * 
     * @param configProperty
     */
    public void removeProperty( ConfigProperty configProperty )
    {
        getProperties().remove( configProperty );
    } //-- void removeProperty( ConfigProperty )

    /**
     * Set name of this configuration.
     * 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    } //-- void setName( String )

    /**
     * Set properties.
     * 
     * @param properties
     */
    public void setProperties( java.util.List/*<ConfigProperty>*/ properties )
    {
        this.properties = properties;
    } //-- void setProperties( java.util.List )

}
