/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.2-SNAPSHOT on 2009-12-16 07:21:29,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.plexus.components.sec.dispatcher.model;

/**
 * generic property - name/value pair.
 * 
 * @version $Revision$ $Date$
 */
public class ConfigProperty
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * name of this property.
     */
    private String name;

    /**
     * value of this property.
     */
    private String value;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get name of this property.
     * 
     * @return String
     */
    public String getName()
    {
        return this.name;
    } //-- String getName()

    /**
     * Get value of this property.
     * 
     * @return String
     */
    public String getValue()
    {
        return this.value;
    } //-- String getValue()

    /**
     * Set name of this property.
     * 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    } //-- void setName( String )

    /**
     * Set value of this property.
     * 
     * @param value
     */
    public void setValue( String value )
    {
        this.value = value;
    } //-- void setValue( String )

}
