/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.2-SNAPSHOT on 2009-12-16 07:21:29,
 any modifications will be overwritten.
 ==============================================================
 */

package org.sonatype.plexus.components.sec.dispatcher.model;

/**
 * Class SettingsSecurity.
 * 
 * @version $Revision$ $Date$
 */
public class SettingsSecurity
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * encrypted master password.
     */
    private String master;

    /**
     * reference to the location of the security file.
     */
    private String relocation;

    /**
     * Field configurations.
     */
    private java.util.List/*<Config>*/ configurations;

    /**
     * Field modelEncoding.
     */
    private String modelEncoding = "UTF-8";


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addConfiguration.
     * 
     * @param config
     */
    public void addConfiguration( Config config )
    {
        getConfigurations().add( config );
    } //-- void addConfiguration( Config )

    /**
     * Method getConfigurations.
     * 
     * @return List
     */
    public java.util.List/*<Config>*/ getConfigurations()
    {
        if ( this.configurations == null )
        {
            this.configurations = new java.util.ArrayList/*<Config>*/();
        }

        return this.configurations;
    } //-- java.util.List/*<Config>*/ getConfigurations()

    /**
     * Get encrypted master password.
     * 
     * @return String
     */
    public String getMaster()
    {
        return this.master;
    } //-- String getMaster()

    /**
     * Get the modelEncoding field.
     * 
     * @return String
     */
    public String getModelEncoding()
    {
        return this.modelEncoding;
    } //-- String getModelEncoding()

    /**
     * Get reference to the location of the security file.
     * 
     * @return String
     */
    public String getRelocation()
    {
        return this.relocation;
    } //-- String getRelocation()

    /**
     * Method removeConfiguration.
     * 
     * @param config
     */
    public void removeConfiguration( Config config )
    {
        getConfigurations().remove( config );
    } //-- void removeConfiguration( Config )

    /**
     * Set named configurations.
     * 
     * @param configurations
     */
    public void setConfigurations( java.util.List/*<Config>*/ configurations )
    {
        this.configurations = configurations;
    } //-- void setConfigurations( java.util.List )

    /**
     * Set encrypted master password.
     * 
     * @param master
     */
    public void setMaster( String master )
    {
        this.master = master;
    } //-- void setMaster( String )

    /**
     * Set the modelEncoding field.
     * 
     * @param modelEncoding
     */
    public void setModelEncoding( String modelEncoding )
    {
        this.modelEncoding = modelEncoding;
    } //-- void setModelEncoding( String )

    /**
     * Set reference to the location of the security file.
     * 
     * @param relocation
     */
    public void setRelocation( String relocation )
    {
        this.relocation = relocation;
    } //-- void setRelocation( String )

}
